CREATE DATABASE SoftUni
USE SoftUni

CREATE TABLE Towns(
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL
)
CREATE TABLE Addresses(
Id INT PRIMARY KEY IDENTITY,
AdressText NVARCHAR(100) NOT NULL,
TownId INT FOREIGN KEY REFERENCES Towns(Id) NOT NULL
)
CREATE TABLE Departments(
Id INT PRIMARY KEY IDENTITY,

)
CREATE TABLE Employees(
Id INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
MuddleName NVARCHAR(50),
LastName NVARCHAR(50) NOT NULL,
Department INT FOREIGN KEY REFERENCES Departments(Id) NOT NULL,
HireDate DATE NOT NULL,
Salary DECIMAL(7,2) NOT NULL,
AdderssId INT FOREIGN KEY REFERENCES 

)

